(require 'cl-lib)
(require 'ert)
(defvar my/test-source-root
  (file-name-directory (directory-file-name
                        (file-name-directory (or load-file-name buffer-file-name)))))
(setq user-emacs-directory (file-name-as-directory (make-temp-file "dotemacs-test-" t)))
(copy-file (expand-file-name "init.el" my/test-source-root)
           (expand-file-name "init.el" user-emacs-directory))
(dolist (name '("inits" "themes"))
  (copy-directory (expand-file-name name my/test-source-root)
                  (expand-file-name name user-emacs-directory) nil t t))
(require 'server)
(cl-letf (((symbol-function 'server-running-p) (lambda (&rest _) t)))
  (load (expand-file-name "init.el" user-emacs-directory) nil t))
(ert-deftest shared-defaults ()
  (should (equal (key-binding (kbd "s-<left>")) 'skip-chars-backward-dwim))
  (should (member my/junk-directory my/tmp-managed-directories))
  (should (equal my/tmp-retention-days 30))
  (should (equal (key-binding (kbd "s-n")) 'my-find-file-other-window)))
(ert-deftest protected-notes ()
  (let* ((my/junk-directory (make-temp-file "persistent-notes-" t))
         (my/junk-auto-delete nil)
         (my/tmp-managed-directories nil)
         (file (expand-file-name "old.txt" my/junk-directory)))
    (with-temp-file file (insert "keep"))
    (set-file-times file (time-subtract (current-time) (days-to-time 90)))
    (load (expand-file-name "inits/behaviour.init.el" my/test-source-root) nil t)
    (my/tmp-garbage-collect)
    (should (file-exists-p file))))
(ert-deftest personal-overrides ()
  (let ((saved-map (current-global-map)))
  (unwind-protect
      (progn
        (use-global-map (copy-keymap saved-map))
  (load (expand-file-name "examples/macos-overrides.el" my/test-source-root) nil t)
  (should (eq (key-binding (kbd "s-<left>")) 'beginning-of-visual-line))
  (should (eq (key-binding (kbd "C-a")) 'move-beginning-of-line)))
    (use-global-map saved-map))))
(ert-deftest malformed-history ()
  (let* ((my-hist-dir (make-temp-file "dotemacs-history-" t))
         (my-hist-last-files (expand-file-name "last-files" my-hist-dir)))
    (dolist (content '("nil" "unexpected-symbol" "(bad-entry)" "((42 . 7))" "broken(:"))
      (with-temp-file my-hist-last-files (insert content))
      (should (load (expand-file-name "inits/util.init.el" my/test-source-root) nil t)))))
(ert-deftest macos-personal-settings ()
  (let ((my/junk-directory my/junk-directory)
        (my/junk-auto-delete my/junk-auto-delete)
        (my/use-mozc my/use-mozc)
        (my/tmp-managed-directories nil))
    (load (expand-file-name "examples/macos-settings.el" my/test-source-root) nil t)
    (load (expand-file-name "inits/behaviour.init.el" my/test-source-root) nil t)
    (should-not my/use-mozc)
    (should-not (member my/junk-directory my/tmp-managed-directories))))
(ert-run-tests-batch-and-exit)
